-- ============================================
-- SCHEMA + DONNÉES : LoL Shop - Les Sbires Lécheurs
-- ============================================

SET NAMES utf8mb4;
SET foreign_key_checks = 0;

-- --------------------------------------------
-- TABLE : champions
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS champions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(100) NOT NULL,
    titre VARCHAR(150),
    description TEXT,
    role ENUM('Assassin','Combattant','Mage','Tireur','Support','Tank') NOT NULL,
    genre ENUM('Masculin','Féminin','Non-binaire','Machine','Entité Cosmique','Yordle','Esprit') NOT NULL,
    prix_rp INT NOT NULL,
    stock INT NOT NULL DEFAULT 50,
    reduction DECIMAL(5,2) DEFAULT 0,
    devise VARCHAR(10) DEFAULT 'RP',
    image1 VARCHAR(255),
    image2 VARCHAR(255),
    image3 VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------
-- TABLE : skins
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS skins (
    id INT PRIMARY KEY AUTO_INCREMENT,
    champion_id INT NOT NULL,
    nom VARCHAR(150) NOT NULL,
    prix_rp INT NOT NULL,
    FOREIGN KEY (champion_id) REFERENCES champions(id) ON DELETE CASCADE
);

-- --------------------------------------------
-- TABLE : chromas
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS chromas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    skin_id INT NOT NULL,
    nom VARCHAR(100) NOT NULL,
    FOREIGN KEY (skin_id) REFERENCES skins(id) ON DELETE CASCADE
);

-- --------------------------------------------
-- TABLE : icon_avatars
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS icon_avatars (
    id INT PRIMARY KEY AUTO_INCREMENT,
    champion_id INT NOT NULL,
    nom VARCHAR(150) NOT NULL,
    FOREIGN KEY (champion_id) REFERENCES champions(id) ON DELETE CASCADE
);

-- --------------------------------------------
-- TABLE : users
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(100),
    prenom VARCHAR(100),
    email VARCHAR(150) UNIQUE NOT NULL,
    mot_de_passe VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- --------------------------------------------
-- TABLE : adresses
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS adresses (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    rue VARCHAR(255),
    ville VARCHAR(100),
    code_postal VARCHAR(10),
    pays VARCHAR(100),
    est_principale BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- --------------------------------------------
-- TABLE : panier
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS panier (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    champion_id INT NOT NULL,
    skin_id INT,
    chroma_id INT,
    icon_avatar_id INT,
    quantite INT DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (champion_id) REFERENCES champions(id),
    FOREIGN KEY (skin_id) REFERENCES skins(id),
    FOREIGN KEY (chroma_id) REFERENCES chromas(id),
    FOREIGN KEY (icon_avatar_id) REFERENCES icon_avatars(id)
);

-- --------------------------------------------
-- TABLE : commandes
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS commandes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    adresse_id INT,
    statut ENUM('en attente','payée','expédiée','livrée') DEFAULT 'en attente',
    total DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (adresse_id) REFERENCES adresses(id)
);

-- --------------------------------------------
-- TABLE : commande_items
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS commande_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    commande_id INT NOT NULL,
    champion_id INT NOT NULL,
    skin_id INT,
    chroma_id INT,
    icon_avatar_id INT,
    quantite INT,
    prix_unitaire DECIMAL(10,2),
    FOREIGN KEY (commande_id) REFERENCES commandes(id) ON DELETE CASCADE,
    FOREIGN KEY (champion_id) REFERENCES champions(id)
);

-- --------------------------------------------
-- TABLE : favoris
-- --------------------------------------------
CREATE TABLE IF NOT EXISTS favoris (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    champion_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (champion_id) REFERENCES champions(id) ON DELETE CASCADE,
    UNIQUE KEY unique_favori (user_id, champion_id)
);

SET foreign_key_checks = 1;

-- ============================================
-- INSERTIONS
-- ============================================

-- INSERT champions
INSERT INTO champions (nom, titre, description, role, genre, prix_rp, stock, reduction, devise, image1, image2, image3) VALUES
  ('Kai\'Sa', 'Fille du Vide', 'Kai\'Sa a survécu grâce à sa ténacité et à sa symbiose avec une combinaison de Vide vivante. Chasseresse solitaire, elle a appris à tuer pour survivre dans les profondeurs des abysses du Vide. Aujourd\'hui mi-humaine mi-Vide, elle cherche à prouver qu\'elle n\'est pas un monstre, malgré ce que le monde pense d\'elle.', 'Tireur', 'Féminin', 975, 163, 0, 'RP', '/assets/img/kaisa_1.png', '/assets/img/kaisa_2.png', '/assets/img/kaisa_3.png'),
  ('Jinx', 'La Canonière Déchaînée', 'Jinx est une criminelle imprévisible originaire de Zaun, qui sème le chaos et la destruction partout où elle passe. Armée d\'un arsenal d\'armes dévastatrices, elle adore semer la panique chez ses ennemis avec des explosions spectaculaires et des actes de vandalisme à grande échelle. Tout le monde la craint, et elle adore ça.', 'Tireur', 'Féminin', 880, 70, 10, 'RP', '/assets/img/jinx_1.png', '/assets/img/jinx_2.png', '/assets/img/jinx_3.png'),
  ('Caitlyn', 'La Shérif de Piltover', 'Caitlyn est la meilleure chasseresse de primes de Piltover, connue pour son sens de la justice inflexible et sa précision redoutable au fusil de précision. Née dans une famille aisée, elle a choisi de défendre l\'ordre plutôt que de profiter de ses privilèges, affrontant sans relâche la corruption qui ronge sa ville bien-aimée.', 'Tireur', 'Féminin', 880, 186, 0, 'RP', '/assets/img/caitlyn_1.png', '/assets/img/caitlyn_2.png', '/assets/img/caitlyn_3.png'),
  ('Ashe', 'La Flèche de Glace', 'Ashe est la guerrière-reine du clan Avarosan, l\'une des plus grandes tribus freljordaises. Pragmatique et déterminée, elle manie l\'arc enchanté des anciens rois de glace pour unifier les tribus du Freljord sous sa bannière. Elle croit que la paix est possible, même dans les terres les plus sauvages du monde.', 'Tireur', 'Féminin', 450, 199, 0, 'RP', '/assets/img/ashe_1.png', '/assets/img/ashe_2.png', '/assets/img/ashe_3.png'),
  ('Ezreal', 'L\'Explorateur Prodige', 'Ezreal est un aventurier prodige originaire de Piltover, doté d\'un talent naturel pour la magie et l\'exploration. Arborant un gantelet magique qu\'il a découvert dans une tombe shuriman, il parcourt le monde à la recherche de reliques anciennes et de défis palpitants, toujours avec un sourire charmeur aux lèvres.', 'Tireur', 'Masculin', 880, 159, 0, 'RP', '/assets/img/ezreal_1.png', '/assets/img/ezreal_2.png', '/assets/img/ezreal_3.png'),
  ('Miss Fortune', 'La Chasseuse de Primes', 'Miss Fortune est une chasseuse de primes redoutée des mers de Runeterra. Après avoir vu sa mère assassinée par le tristement célèbre Gangplank, elle a juré de se venger et de protéger les innocents. Armée de ses deux pistolets Shock et Awe, elle traque les criminels sans pitié tout en gardant son charme légendaire.', 'Tireur', 'Féminin', 450, 127, 10, 'RP', '/assets/img/miss_fortune_1.png', '/assets/img/miss_fortune_2.png', '/assets/img/miss_fortune_3.png'),
  ('Yasuo', 'L\'Exilé Infaillible', 'Yasuo est un épéiste errant qui porte le poids d\'une fausse accusation de meurtre. Autrefois étudiant prometteur d\'une école d\'escrime iônienne, il est aujourd\'hui pourchassé par ceux qui croient qu\'il a tué son maître. Avec son vent enchanté et sa lame rapide comme l\'éclair, il cherche la vérité tout en combattant pour sa survie.', 'Combattant', 'Masculin', 975, 76, 30, 'RP', '/assets/img/yasuo_1.png', '/assets/img/yasuo_2.png', '/assets/img/yasuo_3.png'),
  ('Yone', 'L\'Âme Non-Apaisée', 'Yone est le frère aîné de Yasuo, tué par ce dernier lors d\'un duel fratricide. Revenu des Enfers après avoir vaincu un démon azakana, il porte désormais le masque de sa proie et une lame d\'âme. Hanté par ses démons intérieurs, il cherche à comprendre ce qui a rendu son frère si dangereux et à protéger ceux qu\'il aimait.', 'Combattant', 'Masculin', 975, 134, 25, 'RP', '/assets/img/yone_1.png', '/assets/img/yone_2.png', '/assets/img/yone_3.png'),
  ('Lux', 'La Dame de Lumière', 'Lux est une mage lumineuse originaire de Demacia, une nation qui craint et réprime la magie. Née avec le don de manipuler la lumière, elle cache ses pouvoirs tout en servant secrètement la cause de ceux qui veulent réformer son pays. Vive et enthousiaste, elle croit fermement que la lumière peut dissiper toutes les ténèbres.', 'Mage', 'Féminin', 450, 170, 15, 'RP', '/assets/img/lux_1.png', '/assets/img/lux_2.png', '/assets/img/lux_3.png'),
  ('Ahri', 'la Renarde à Neuf Queues', 'Ahri est une vastaya dont la nature magique lui permet de se connecter aux émotions humaines et de dévorer leur essence vitale. Tourmentée par les fragments de souvenirs qu\'elle absorbe de ses victimes, elle cherche à retrouver son véritable foyer tout en apprenant à contrôler ses pouvoirs. Séduisante mais dangereuse, elle navigue entre deux mondes.', 'Mage', 'Féminin', 880, 91, 0, 'RP', '/assets/img/ahri_1.png', '/assets/img/ahri_2.png', '/assets/img/ahri_3.png'),
  ('Zed', 'le Maître des Ombres', 'Zed est le maître fondateur de l\'Ordre des Ombres, une organisation ninja qui utilise les arts sombres interdits. Après avoir trahi son maître pour s\'emparer de la puissance des ombres, il a transformé son dojo en une armée redoutable. Impitoyable et pragmatique, il croit que la fin justifie les moyens pour protéger Ionia.', 'Assassin', 'Masculin', 975, 21, 0, 'RP', '/assets/img/zed_1.png', '/assets/img/zed_2.png', '/assets/img/zed_3.png'),
  ('Thresh', 'le Geôlier de la Chaîne', 'Thresh est un spectre sadique qui tourmente les âmes des vivants et des morts. Autrefois gardien des cryptes de la Côte des Ombres, il a développé une obsession malsaine pour la collection d\'âmes qu\'il emprisonne dans sa lanterne maudite. Cruel et patient, il tisse des pièges élaborés pour capturer ses proies avec une jouissance perverse.', 'Support', 'Esprit', 975, 60, 0, 'RP', '/assets/img/thresh_1.png', '/assets/img/thresh_2.png', '/assets/img/thresh_3.png'),
  ('Akali', 'La Tueuse Renégate', 'Akali est une ninja renégate qui a abandonné l\'Ordre de l\'Ombre pour forger son propre destin. Fille d\'une ancienne membre de l\'Ordre, elle a maîtrisé les arts de l\'ombre avant de se rebeller contre ses enseignements restrictifs. Rapide, létale et indépendante, elle défend à sa façon les opprimés d\'Ionia contre ceux qui abusent de leur pouvoir.', 'Assassin', 'Féminin', 975, 198, 0, 'RP', '/assets/img/akali_1.png', '/assets/img/akali_2.png', '/assets/img/akali_3.png'),
  ('Katarina', 'La Lame Sinistre', 'Katarina est une assassine d\'élite de Noxus, fille du général Du Couteau. Impétueuse et passionnée, elle a grandi dans l\'ombre de son père avant de tracer sa propre voie sanglante sur les champs de bataille. Maîtresse des lames et de la mobilité, elle frappe avec une précision dévastatrice et disparaît avant que ses ennemis ne comprennent ce qui s\'est passé.', 'Assassin', 'Féminin', 450, 128, 0, 'RP', '/assets/img/katarina_1.png', '/assets/img/katarina_2.png', '/assets/img/katarina_3.png'),
  ('Lee Sin', 'le Moine Aveugle', 'Lee Sin est un moine de combat légendaire d\'Ionia qui s\'est aveuglé lui-même pour expier ses péchés. Guidé par les esprits du dragon et sa maîtrise de l\'énergie spirituelle, il combat avec une agilité et une puissance remarquables malgré son handicap. Sage et humble, il voyage à travers Ionia pour réparer les torts qu\'il a causés dans sa jeunesse impétueuse.', 'Combattant', 'Masculin', 880, 107, 15, 'RP', '/assets/img/lee_sin_1.png', '/assets/img/lee_sin_2.png', '/assets/img/lee_sin_3.png'),
  ('Ekko', 'le Gamin qui A Fracturé le Temps', 'Ekko est un jeune génie des rues de Zaun qui a construit un appareil capable de manipuler le temps. Avec son Z-Drive, il peut rebobiner les quelques secondes précédentes pour corriger ses erreurs et surprendre ses ennemis. Créatif et débrouillard, il utilise ses talents pour protéger son quartier et rêve d\'un monde meilleur pour les habitants des bas-fonds.', 'Assassin', 'Masculin', 975, 91, 10, 'RP', '/assets/img/ekko_1.png', '/assets/img/ekko_2.png', '/assets/img/ekko_3.png'),
  ('Vi', 'la Vengeance de Piltover', 'Vi est une officière de l\'Exécutoire de Piltover, connue pour son style direct et ses énormes gantelets hextech. Ancienne criminelle des bidonvilles de Zaun, elle a troqué la vie de hors-la-loi pour celle d\'agent de la loi, même si ses méthodes restent aussi brutales qu\'avant. Franche et impulsive, elle fonce dans le tas avant de réfléchir aux conséquences.', 'Combattant', 'Féminin', 975, 59, 0, 'RP', '/assets/img/vi_1.png', '/assets/img/vi_2.png', '/assets/img/vi_3.png'),
  ('Sett', 'le Boss', 'Sett est un bagarreur professionnel qui s\'est hissé du bas de l\'échelle jusqu\'au sommet du monde des combats clandestins de Ionia. Fils d\'un père vastaya absent et d\'une mère humaine dévouée, il a appris très tôt que seuls la force et la détermination permettent de survivre. Fier de ses origines, il dirige maintenant ses arènes d\'une poigne de fer.', 'Combattant', 'Masculin', 975, 75, 10, 'RP', '/assets/img/sett_1.png', '/assets/img/sett_2.png', '/assets/img/sett_3.png'),
  ('Leona', 'la Radieuse Aube', 'Leona est une guerrière solaire des Rakkori, un ordre de soldats qui canalisent le pouvoir du soleil. Armée d\'une épée et d\'un bouclier imbibés de lumière solaire, elle protège ses alliés et punit les ennemis avec la chaleur ardente de l\'astre diurne. Déterminée et courageuse, elle est convaincue que la lumière du soleil peut purifier le monde de ses ténèbres.', 'Tank', 'Féminin', 450, 106, 0, 'RP', '/assets/img/leona_1.png', '/assets/img/leona_2.png', '/assets/img/leona_3.png'),
  ('Seraphine', 'la Chanteuse Enchanteresse', 'Seraphine est une jeune musicienne de Piltover qui possède une connexion mystique avec les émotions des autres. Née avec la capacité d\'entendre les âmes des gens, elle utilise sa musique pour amplifier ces voix et unir les gens autour d\'elle. Optimiste et empathique, elle croit sincèrement que la musique peut changer le monde et guérir les blessures les plus profondes.', 'Support', 'Féminin', 975, 46, 0, 'RP', '/assets/img/seraphine_1.png', '/assets/img/seraphine_2.png', '/assets/img/seraphine_3.png'),
  ('Blitzcrank', 'le Grand Golem à Vapeur', 'Blitzcrank est un golem à vapeur créé dans les laboratoires de Zaun pour aider à nettoyer les déchets dangereux. Doué d\'une intelligence artificielle évoluée, il a développé sa propre personnalité et son propre sens moral. Animé par un désir sincère d\'aider les habitants de Zaun, il patrouille les rues en utilisant son poing à roquette pour secourir ceux qui en ont besoin.', 'Support', 'Machine', 450, 43, 0, 'RP', '/assets/img/blitzcrank_1.png', '/assets/img/blitzcrank_2.png', '/assets/img/blitzcrank_3.png'),
  ('Nautilus', 'le Titan des Profondeurs', 'Nautilus est un colosse des profondeurs marines, autrefois simple plongeur trahi par son capitaine et abandonné au fond de l\'océan. Fusionné avec sa combinaison de plongée et habité par une entité mystérieuse des profondeurs, il revient à la surface pour demander des comptes à ceux qui ont trahi leur parole. Lent mais inexorable comme les marées, il traîne ses proies dans les abysses.', 'Tank', 'Masculin', 880, 117, 0, 'RP', '/assets/img/nautilus_1.png', '/assets/img/nautilus_2.png', '/assets/img/nautilus_3.png'),
  ('Jhin', 'le Virtuose', 'Jhin est un tueur en série qui considère le meurtre comme une forme d\'art. Ancien acteur de théâtre iônien devenu assassin psychopathe, il met en scène ses crimes avec une précision et une créativité macabres. Obsédé par le chiffre quatre et la perfection esthétique, il laisse derrière lui des tableaux vivants horrifiques qui fascinent autant qu\'ils terrorisent.', 'Tireur', 'Masculin', 975, 44, 0, 'RP', '/assets/img/jhin_1.png', '/assets/img/jhin_2.png', '/assets/img/jhin_3.png'),
  ('Viego', 'le Roi Ruiné', 'Viego est l\'ancien roi de Camavor dont l\'amour obsessionnel pour sa femme mourante a plongé le monde dans la Ruine. Après la mort d\'Isolde, il a cherché à la ressusciter par tous les moyens, déclenchant une catastrophe qui a corrompu des continents entiers. Aujourd\'hui spectre puissant et dément, il cherche l\'âme de sa bien-aimée à travers les corps qu\'il possède.', 'Assassin', 'Masculin', 975, 111, 0, 'RP', '/assets/img/viego_1.png', '/assets/img/viego_2.png', '/assets/img/viego_3.png'),
  ('Sylas', 'le Sans-Chaînes', 'Sylas est un mage né dans les bas-fonds de Demacia, emprisonné dès l\'enfance pour ses pouvoirs magiques interdits. Après des années de captivité et de torture, il s\'est échappé en volant les pouvoirs de ses geôliers et a déclenché une révolution des mages opprimés. Charismatique et impitoyable, il lutte pour la liberté mais ses méthodes violentes remettent en question ses idéaux.', 'Mage', 'Masculin', 975, 108, 0, 'RP', '/assets/img/sylas_1.png', '/assets/img/sylas_2.png', '/assets/img/sylas_3.png'),
  ('Zeri', 'la Étincelle de Zaun', 'Zeri est une jeune femme de Zaun dont le corps canalise naturellement l\'électricité de façon incontrôlable. Grandie dans un quartier populaire de la ville basse, elle a appris à maîtriser ses pouvoirs pour protéger sa communauté. Fougueuse et énergique comme la foudre, elle se bat contre l\'oppression avec ses pistolets électriques et son cœur généreux.', 'Tireur', 'Féminin', 975, 174, 0, 'RP', '/assets/img/zeri_1.png', '/assets/img/zeri_2.png', '/assets/img/zeri_3.png'),
  ('Samira', 'la Rose du Désert', 'Samira est une mercenaire noxienne d\'origine shuriman connue pour son style de combat flamboyant et sa recherche obsessionnelle du frisson. Ayant perdu sa famille dans le conflit entre Noxus et Shurima, elle s\'est construite une réputation de combattante incomparable qui mélange pistolets et épée avec une grâce mortelle. Elle vit pour le danger et adore impressionner le public.', 'Tireur', 'Féminin', 975, 87, 0, 'RP', '/assets/img/samira_1.png', '/assets/img/samira_2.png', '/assets/img/samira_3.png'),
  ('Vayne', 'la Chasseuse de Nuit', 'Vayne est une chasseuse de monstres impitoyable qui a consacré sa vie à éradiquer les créatures obscures après avoir vu ses parents dévorés par un démon. Armée d\'une arbalète à boulons d\'argent et d\'un grappin, elle traque inlassablement les entités corrompues dans les ténèbres. Sombre et déterminée, elle est prête à tout sacrifier pour accomplir sa mission.', 'Tireur', 'Féminin', 880, 31, 0, 'RP', '/assets/img/vayne_1.png', '/assets/img/vayne_2.png', '/assets/img/vayne_3.png'),
  ('Draven', 'le Gouverneur des Arènes', 'Draven est un exécuteur noxien qui a transformé son travail en spectacle de gladiateurs. Narcissique et flamboyant, il jongle avec ses haches rotatives devant des foules en délire qui scandent son nom. Frère de Darius, il a choisi la gloire personnelle plutôt que la discipline militaire, créant son propre culte de la personnalité autour de ses exécutions spectaculaires.', 'Tireur', 'Masculin', 880, 137, 0, 'RP', '/assets/img/draven_1.png', '/assets/img/draven_2.png', '/assets/img/draven_3.png'),
  ('Tristana', 'la Gunner Yordle', 'Tristana est une yordle soldat de Bandle City, animée par un enthousiasme contagieux pour l\'aventure et les gros canons. Recrutée dans la Brigade des Megling, elle parcourt Runeterra à la recherche d\'action et d\'excitation, sautant dans la bataille avec un sourire aux lèvres et son canon Boum sur l\'épaule. Sa naïveté cache une guerrière redoutablement efficace.', 'Tireur', 'Yordle', 880, 157, 0, 'RP', '/assets/img/tristana_1.png', '/assets/img/tristana_2.png', '/assets/img/tristana_3.png'),
  ('Lulu', 'la Fée Farfelue', 'Lulu est une yordle qui a passé tant de temps dans le royaume des fées qu\'elle a perdu le sens des réalités ordinaires. Accompagnée de son ami féérique Pix, elle lance des sorts capricieux qui peuvent transformer les ennemis en écureuils ou faire grandir les alliés. Excentrique et bienveillante à sa façon, elle aide sincèrement ses amis même si ses méthodes semblent parfois chaotiques.', 'Support', 'Yordle', 880, 51, 0, 'RP', '/assets/img/lulu_1.png', '/assets/img/lulu_2.png', '/assets/img/lulu_3.png'),
  ('Nami', 'la Maréchaussée des Abysses', 'Nami est une sirène des profondeurs qui a bravé les terres émergées pour sauver son peuple. Envoyée en mission pour récupérer un objet sacré échangeable contre un cristal de lune vital pour sa tribu, elle découvre un monde de surface bien plus complexe qu\'imaginé. Courageuse et déterminée malgré sa vulnérabilité hors de l\'eau, elle forge des alliances inattendues pour accomplir sa quête.', 'Support', 'Non-binaire', 880, 116, 0, 'RP', '/assets/img/nami_1.png', '/assets/img/nami_2.png', '/assets/img/nami_3.png'),
  ('Soraka', 'l\'Enfant des Étoiles', 'Soraka est une créature céleste qui a renoncé à son immortalité pour soigner les blessures des mortels. Autrefois habitante des étoiles, elle fut blessée par le mage Warwick et choisit de rester sur Runeterra pour expier en guérissant les souffrances qu\'elle a vues. Compatissante jusqu\'au sacrifice, elle puise dans sa propre vitalité pour maintenir ses alliés en vie.', 'Support', 'Entité Cosmique', 450, 40, 0, 'RP', '/assets/img/soraka_1.png', '/assets/img/soraka_2.png', '/assets/img/soraka_3.png'),
  ('Yuumi', 'la Chatte Magique', 'Yuumi est une chatte magique à la recherche de son maître disparu, le livre magique Norumii. Capable de s\'attacher à des alliés et de lancer des sorts depuis leur dos, elle parcourt Runeterra avec une curiosité insatiable. Mignonne mais parfois exaspérante, elle apporte soins et soutien à ceux qu\'elle accompagne tout en cherchant des indices sur la disparition de son vieil ami.', 'Support', 'Féminin', 975, 161, 0, 'RP', '/assets/img/yuumi_1.png', '/assets/img/yuumi_2.png', '/assets/img/yuumi_3.png'),
  ('Orianna', 'la Dame des Rouages', 'Orianna est une jeune femme transformée en être mécanique par son père inventeur pour la sauver après de graves blessures. Mi-humaine mi-automate, elle explore le monde avec une curiosité analytique, accompagnée de la Boule, un engin mécanique qu\'elle commande à distance. Cherchant à comprendre les émotions humaines qu\'elle a du mal à ressentir, elle imite les comportements sociaux avec une grâce étrange.', 'Mage', 'Machine', 880, 95, 30, 'RP', '/assets/img/orianna_1.png', '/assets/img/orianna_2.png', '/assets/img/orianna_3.png'),
  ('Viktor', 'le Héraut de la Technologie', 'Viktor est un scientifique visionnaire de Zaun qui croit que l\'évolution technologique est la seule voie vers un avenir meilleur pour l\'humanité. Ayant remplacé ses propres membres par des améliorations cybernétiques, il développe l\'Hexcore pour fusionner magie et machine. Froid et méthodique, il sacrifie tout au nom du progrès, convaincu que la chair est une faiblesse à surmonter.', 'Mage', 'Masculin', 880, 180, 0, 'RP', '/assets/img/viktor_1.png', '/assets/img/viktor_2.png', '/assets/img/viktor_3.png'),
  ('Syndra', 'la Souveraine Obscure', 'Syndra est une mage iônienne d\'une puissance phénoménale qui a été réprimée et exilée pour ses pouvoirs jugés dangereux. Trahie par son mentor qui cherchait à la contrôler, elle a brisé ses chaînes et embrasse maintenant sa vraie puissance sans limite ni restriction. Amère et déterminée, elle cherche à se venger de ceux qui l\'ont opprimée et à prouver que sa magie n\'appartient qu\'à elle.', 'Mage', 'Féminin', 880, 178, 0, 'RP', '/assets/img/syndra_1.png', '/assets/img/syndra_2.png', '/assets/img/syndra_3.png'),
  ('Cassiopeia', 'la Malédiction du Serpent', 'Cassiopeia est l\'une des filles du général Du Couteau de Noxus, transformée en créature mi-femme mi-serpent après avoir été mordue dans une tombe shuriman maudite. Autrefois connue pour sa beauté et sa ruse diplomatique, elle utilise maintenant ses pouvoirs venimeux et son regard pétrifiant pour assouvir ses ambitions politiques depuis les ombres de l\'empire noxien.', 'Mage', 'Féminin', 880, 112, 0, 'RP', '/assets/img/cassiopeia_1.png', '/assets/img/cassiopeia_2.png', '/assets/img/cassiopeia_3.png'),
  ('Twisted Fate', 'le Maître des Cartes', 'Twisted Fate est un joueur professionnel et escroqueur qui a fait du monde entier son casino. Originaire des bayous de Runeterra, il a acquis des pouvoirs magiques lors d\'un rituel qui a mal tourné et utilise ses cartes enchantées pour manipuler le destin. Charmeur et imprévisible, il navigue entre escroqueries et aventures, toujours prêt à miser gros quand les enjeux sont à la hauteur.', 'Mage', 'Masculin', 450, 167, 0, 'RP', '/assets/img/twisted_fate_1.png', '/assets/img/twisted_fate_2.png', '/assets/img/twisted_fate_3.png'),
  ('Fizz', 'l\'Espiègle des Mers', 'Fizz est une mystérieuse créature aquatique qui s\'est installée dans les canaux de Bilgewater après que sa cité natale fut détruite. Joueur et espiègle, il glisse entre les attaques avec une agilité déconcertante et attaque avec son trident enchanté. Personne ne sait vraiment d\'où vient Fizz ni à quelle espèce il appartient, mais sa présence dans les eaux de Bilgewater est désormais une légende locale.', 'Assassin', 'Masculin', 880, 69, 0, 'RP', '/assets/img/fizz_1.png', '/assets/img/fizz_2.png', '/assets/img/fizz_3.png'),
  ('Talon', 'la Lame de l\'Exil', 'Talon est un assassin noxien élevé dans les rues comme orphelin avant d\'être recruté par la famille Du Couteau. Maître du combat rapproché et de l\'infiltration, il a été formé aux arts les plus létaux de Noxus. Silencieux et efficace, il exécute ses contrats avec une précision redoutable, cherchant toujours à se mesurer à des adversaires plus forts pour tester ses limites.', 'Assassin', 'Masculin', 880, 200, 30, 'RP', '/assets/img/talon_1.png', '/assets/img/talon_2.png', '/assets/img/talon_3.png'),
  ('Irelia', 'la Lame Dansante', 'Irelia est une guerrière iônienne qui a pris les armes pour défendre sa patrie contre l\'invasion noxienne. Maîtrisant l\'art des lames volantes de sa famille, elle a mené la résistance avec une férocité qui cachait son profond traumatisme de guerre. Aujourd\'hui chef militaire respectée, elle porte le poids de ses victoires et cherche à trouver la paix dans un Ionia qui continue de se transformer.', 'Combattant', 'Féminin', 880, 37, 0, 'RP', '/assets/img/irelia_1.png', '/assets/img/irelia_2.png', '/assets/img/irelia_3.png'),
  ('Fiora', 'la Grande Duelliste', 'Fiora est la plus grande duelliste de Demacia, une femme de la haute noblesse qui a restauré l\'honneur de sa famille après la trahison de son père. Arrogante et perfectionniste, elle considère le combat comme un art dont elle est la suprême maîtresse. Sa quête de l\'adversaire parfait la pousse à voyager à travers le monde, défiant quiconque ose prétendre pouvoir la surpasser à l\'épée.', 'Combattant', 'Féminin', 880, 31, 0, 'RP', '/assets/img/fiora_1.png', '/assets/img/fiora_2.png', '/assets/img/fiora_3.png'),
  ('Darius', 'la Main de Noxus', 'Darius est le plus redouté des généraux noxiens, un guerrier né dans la pauvreté qui s\'est hissé au sommet de l\'armée par sa seule force et détermination. Incarnation vivante des valeurs noxiennes de puissance et de pragmatisme, il abat les ennemis de l\'empire avec sa hache colossale. Frère aîné de Draven, il méprise l\'exhibitionnisme de son cadet et préfère laisser ses actes parler pour lui.', 'Combattant', 'Masculin', 880, 189, 0, 'RP', '/assets/img/darius_1.png', '/assets/img/darius_2.png', '/assets/img/darius_3.png'),
  ('Garen', 'la Puissance de Demacia', 'Garen est un guerrier d\'élite de Demacia, fier représentant des valeurs de justice et d\'honneur de son pays. Chef des Dauntless Vanguard, il combat avec son épée à deux mains et son bouclier au nom de sa nation. Frère de Lux dont il ignore les pouvoirs magiques, il est en proie à des doutes croissants sur le bien-fondé des lois anti-magie de Demacia.', 'Tank', 'Masculin', 450, 78, 0, 'RP', '/assets/img/garen_1.png', '/assets/img/garen_2.png', '/assets/img/garen_3.png'),
  ('Malphite', 'le Shard of the Monolith', 'Malphite est un être ancien fait de pierre vivante, fragment d\'un monolithe primordial qui existait avant la civilisation. Gardien endormi du monde géologique, il s\'est réveillé pour défendre la terre contre les forces du chaos et de la corruption. Lent comme les plaques tectoniques mais irrésistible comme un tremblement de terre, il écrase ses ennemis avec la puissance brute de la roche.', 'Tank', 'Masculin', 450, 94, 0, 'RP', '/assets/img/malphite_1.png', '/assets/img/malphite_2.png', '/assets/img/malphite_3.png'),
  ('Amumu', 'le Fantôme Maudit', 'Amumu est une petite momie solitaire qui erre dans les ruines de Shurima depuis des millénaires, maudit par une solitude absolue que ses larmes semblent amplifier. Tous ceux qu\'il touche ressentent son désespoir et fuient, renforçant son isolement tragique. Il cherche juste un ami véritable, ignorant que son étreinte mortelle est précisément ce qui rend l\'amitié impossible pour lui.', 'Tank', 'Masculin', 450, 40, 0, 'RP', '/assets/img/amumu_1.png', '/assets/img/amumu_2.png', '/assets/img/amumu_3.png'),
  ('Camille', 'la Steel Shadow', 'Camille est l\'agente d\'élite de la maison Ferros de Piltover, dont le corps a été progressivement amélioré avec des améliorations hextech au fil des décennies. Gardienne des secrets de sa maison et juge implacable de ceux qui menacent ses intérêts, elle se déplace avec une grâce mécanique terrifiante. Froide et méthodique, elle considère l\'émotion comme une faiblesse et la perfection mécanique comme un idéal.', 'Combattant', 'Féminin', 975, 79, 0, 'RP', '/assets/img/camille_1.png', '/assets/img/camille_2.png', '/assets/img/camille_3.png'),
  ('Neeko', 'la Curieuse Caméléonne', 'Neeko est une vastaya surviveuse du clan Oovi-Kat, des caméléons magiques presque entièrement disparus. Dotée du pouvoir de se transformer en n\'importe quelle personne ou créature qu\'elle a observée, elle explore le monde avec une curiosité sans bornes. Seule représentante connue de son espèce, elle cherche d\'autres membres de son clan tout en apprenant à comprendre et accepter sa propre identité unique.', 'Mage', 'Non-binaire', 975, 45, 0, 'RP', '/assets/img/neeko_1.png', '/assets/img/neeko_2.png', '/assets/img/neeko_3.png'),
  ('Smolder', 'le Petit Dragon Choyé', 'Smolder est un jeune dragon élevé parmi les humains qui commence tout juste à découvrir ses pouvoirs de feu. Choyé et quelque peu gâté par ses parents adoptifs humains, il affronte le monde avec une confiance parfois mal placée et un enthousiasme brûlant au sens propre comme au figuré. Mignon mais potentiellement dévastateur, il grandit et apprend au fil de ses aventures en Runeterra.', 'Tireur', 'Masculin', 975, 117, 0, 'RP', '/assets/img/smolder_1.png', '/assets/img/smolder_2.png', '/assets/img/smolder_3.png');

-- INSERT skins
INSERT INTO skins (champion_id, nom, prix_rp) VALUES
  (1, 'Skin de base', 0),
  (1, 'Bullet Angel Kai\'Sa', 1350),
  (1, 'K/DA Kai\'Sa', 1350),
  (1, 'Star Guardian Kai\'Sa', 1820),
  (2, 'Skin de base', 0),
  (2, 'Arcane Jinx', 1350),
  (2, 'Star Guardian Jinx', 1350),
  (2, 'Firecracker Jinx', 1350),
  (3, 'Skin de base', 0),
  (3, 'Arcane Caitlyn', 1350),
  (3, 'Pulsefire Caitlyn', 1820),
  (3, 'Pool Party Caitlyn', 1350),
  (4, 'Skin de base', 0),
  (4, 'Cosmic Queen Ashe', 1820),
  (4, 'Marauder Ashe', 750),
  (4, 'Lunar Empress Ashe', 1350),
  (5, 'Skin de base', 0),
  (5, 'Pulsefire Ezreal', 3250),
  (5, 'Star Guardian Ezreal', 1350),
  (5, 'Ace of Spades Ezreal', 750),
  (6, 'Skin de base', 0),
  (6, 'K/DA Miss Fortune', 1350),
  (6, 'Battle Bunny Miss Fortune', 1350),
  (6, 'Arcade Miss Fortune', 1350),
  (7, 'Skin de base', 0),
  (7, 'High Noon Yasuo', 1350),
  (7, 'Project Yasuo', 1350),
  (7, 'True Damage Yasuo', 1350),
  (8, 'Skin de base', 0),
  (8, 'Spirit Blossom Yone', 1350),
  (8, 'Project Yone', 1350),
  (8, 'Elderwood Yone', 1350),
  (9, 'Skin de base', 0),
  (9, 'Star Guardian Lux', 1350),
  (9, 'Elementalist Lux', 3250),
  (9, 'Cosmic Lux', 1820),
  (10, 'Skin de base', 0),
  (10, 'K/DA Ahri', 1350),
  (10, 'Elderwood Ahri', 1350),
  (10, 'Star Guardian Ahri', 1350),
  (11, 'Skin de base', 0),
  (11, 'Shockblade Zed', 975),
  (11, 'Project Zed', 1350),
  (11, 'Death Sworn Zed', 1350),
  (12, 'Skin de base', 0),
  (12, 'Dark Star Thresh', 1350),
  (12, 'High Noon Thresh', 1350),
  (12, 'Blood Moon Thresh', 975),
  (13, 'Skin de base', 0),
  (13, 'K/DA Akali', 1350),
  (13, 'True Damage Akali', 1350),
  (13, 'Project Akali', 1350),
  (14, 'Skin de base', 0),
  (14, 'High Noon Katarina', 1350),
  (14, 'Slay Belle Katarina', 975),
  (14, 'Project Katarina', 1350),
  (15, 'Skin de base', 0),
  (15, 'God Fist Lee Sin', 1820),
  (15, 'Dragon Fist Lee Sin', 975),
  (15, 'Nightbringer Lee Sin', 1350),
  (16, 'Skin de base', 0),
  (16, 'True Damage Ekko', 1350),
  (16, 'Project Ekko', 1350),
  (16, 'Sandstorm Ekko', 975),
  (17, 'Skin de base', 0),
  (17, 'Arcane Vi', 1350),
  (17, 'Neon Strike Vi', 975),
  (17, 'Officer Vi', 1350),
  (18, 'Skin de base', 0),
  (18, 'Mecha Kingdoms Sett', 1350),
  (18, 'Crime City Nightmare Sett', 1350),
  (18, 'Obsidian Dragon Sett', 1350),
  (19, 'Skin de base', 0),
  (19, 'Pool Party Leona', 1350),
  (19, 'Solar Eclipse Leona', 1350),
  (19, 'Zenith Games Leona', 1350),
  (20, 'Skin de base', 0),
  (20, 'K/DA Seraphine', 1350),
  (20, 'True Damage Seraphine', 1350),
  (20, 'Ocean Song Seraphine', 1350),
  (21, 'Skin de base', 0),
  (21, 'Lancer Paragon Blitzcrank', 1350),
  (21, 'Battlecast Blitzcrank', 1350),
  (21, 'Piltover Customs Blitzcrank', 975),
  (22, 'Skin de base', 0),
  (22, 'Abyssal Nautilus', 975),
  (22, 'Subterranean Nautilus', 750),
  (22, 'Warden Nautilus', 750),
  (23, 'Skin de base', 0),
  (23, 'Blood Moon Jhin', 1350),
  (23, 'Dark Cosmic Jhin', 1820),
  (23, 'High Noon Jhin', 1350),
  (24, 'Skin de base', 0),
  (24, 'Lunar Beast Viego', 1350),
  (24, 'Soul Fighter Viego', 1350),
  (24, 'Sentinel Viego', 1350),
  (25, 'Skin de base', 0),
  (25, 'Freljord Sylas', 750),
  (25, 'Lunar Wraith Sylas', 1350),
  (25, 'Coven Sylas', 1350),
  (26, 'Skin de base', 0),
  (26, 'Withered Rose Zeri', 1350),
  (26, 'Empyrean Zeri', 1350),
  (26, 'Ocean Song Zeri', 1350),
  (27, 'Skin de base', 0),
  (27, 'Withered Rose Samira', 1350),
  (27, 'Crime City Nightmare Samira', 1350),
  (27, 'Soul Fighter Samira', 1350),
  (28, 'Skin de base', 0),
  (28, 'Arclight Vayne', 975),
  (28, 'Project Vayne', 1350),
  (28, 'Soulstealer Vayne', 1350),
  (29, 'Skin de base', 0),
  (29, 'Soul Reaver Draven', 1350),
  (29, 'Draven Draven', 975),
  (29, 'Gladiator Draven', 520),
  (30, 'Skin de base', 0),
  (30, 'Omega Squad Tristana', 1350),
  (30, 'Dragon Trainer Tristana', 1820),
  (30, 'Bewitching Tristana', 1350),
  (31, 'Skin de base', 0),
  (31, 'Star Guardian Lulu', 1350),
  (31, 'Dragon Trainer Lulu', 1820),
  (31, 'Cosmic Enchantress Lulu', 1350),
  (32, 'Skin de base', 0),
  (32, 'Deep Sea Nami', 975),
  (32, 'River Spirit Nami', 975),
  (32, 'Splendid Staff Nami', 1350),
  (33, 'Skin de base', 0),
  (33, 'Star Guardian Soraka', 1350),
  (33, 'Dawnbringer Soraka', 1350),
  (33, 'Pajama Guardian Soraka', 1350),
  (34, 'Skin de base', 0),
  (34, 'Heartseeker Yuumi', 1350),
  (34, 'Bewitching Yuumi', 1350),
  (34, 'Prestige Yuumi', 1820),
  (35, 'Skin de base', 0),
  (35, 'Victorious Orianna', 0),
  (35, 'Sewn Chaos Orianna', 750),
  (35, 'Heartseeker Orianna', 1350),
  (36, 'Skin de base', 0),
  (36, 'Arclight Viktor', 975),
  (36, 'Death Sworn Viktor', 1350),
  (36, 'Gigabuster Viktor', 1350),
  (37, 'Skin de base', 0),
  (37, 'Snow Day Syndra', 1350),
  (37, 'Star Guardian Syndra', 1350),
  (37, 'Coven Syndra', 1820),
  (38, 'Skin de base', 0),
  (38, 'Jade Fang Cassiopeia', 975),
  (38, 'Eternum Cassiopeia', 1350),
  (38, 'Mythic Cassiopeia', 1820),
  (39, 'Skin de base', 0),
  (39, 'Blood Moon Twisted Fate', 975),
  (39, 'Underworld Twisted Fate', 975),
  (39, 'Pulsefire Twisted Fate', 1350),
  (40, 'Skin de base', 0),
  (40, 'Omega Squad Fizz', 1350),
  (40, 'Cottontail Fizz', 975),
  (40, 'Fright Night Fizz', 1350),
  (41, 'Skin de base', 0),
  (41, 'Dragonblade Talon', 975),
  (41, 'Blood Moon Talon', 1350),
  (41, 'Project Talon', 1350),
  (42, 'Skin de base', 0),
  (42, 'Frostblade Irelia', 975),
  (42, 'Nightbringer Irelia', 1350),
  (42, 'Sentinel Irelia', 1350),
  (43, 'Skin de base', 0),
  (43, 'Project Fiora', 1350),
  (43, 'Pool Party Fiora', 1350),
  (43, 'Dawnbringer Fiora', 1350),
  (44, 'Skin de base', 0),
  (44, 'God-King Darius', 1820),
  (44, 'Dunkmaster Darius', 1350),
  (44, 'Woad King Darius', 750),
  (45, 'Skin de base', 0),
  (45, 'God-King Garen', 1820),
  (45, 'Demacia Vice Garen', 1350),
  (45, 'Steel Legion Garen', 1350),
  (46, 'Skin de base', 0),
  (46, 'Obsidian Malphite', 520),
  (46, 'Mecha Malphite', 1350),
  (46, 'Astronaut Malphite', 1350),
  (47, 'Skin de base', 0),
  (47, 'Sad Robot Amumu', 1350),
  (47, 'Surprise Party Amumu', 1350),
  (47, 'Little Knight Amumu', 520),
  (48, 'Skin de base', 0),
  (48, 'Coven Camille', 1350),
  (48, 'Heartseeker Camille', 1350),
  (48, 'Arcana Camille', 1350),
  (49, 'Skin de base', 0),
  (49, 'Winter Wonder Neeko', 1350),
  (49, 'Shan Hai Scrolls Neeko', 1350),
  (49, 'Prestige Neeko', 1820),
  (50, 'Skin de base', 0),
  (50, 'Bewitching Smolder', 1350),
  (50, 'Astronaut Smolder', 1350),
  (50, 'Mythmaker Smolder', 1350);

-- INSERT chromas (liés au premier skin payant)
INSERT INTO chromas (skin_id, nom) VALUES
  (2, 'Amethyst'),
  (2, 'Citrine'),
  (2, 'Emerald'),
  (2, 'Pearl'),
  (2, 'Rose Quartz'),
  (2, 'Ruby'),
  (2, 'Sapphire'),
  (5, 'Catseye'),
  (5, 'Emerald'),
  (5, 'Obsidian'),
  (5, 'Pearl'),
  (5, 'Rose Quartz'),
  (5, 'Ruby'),
  (5, 'Sapphire'),
  (8, 'Amethyst'),
  (8, 'Citrine'),
  (8, 'Obsidian'),
  (8, 'Pearl'),
  (8, 'Rose Quartz'),
  (8, 'Ruby'),
  (8, 'Turquoise'),
  (11, 'Amethyst'),
  (11, 'Catseye'),
  (11, 'Emerald'),
  (11, 'Obsidian'),
  (11, 'Pearl'),
  (11, 'Rose Quartz'),
  (11, 'Sapphire'),
  (14, 'Amethyst'),
  (14, 'Catseye'),
  (14, 'Citrine'),
  (14, 'Emerald'),
  (14, 'Pearl'),
  (14, 'Ruby'),
  (14, 'Sapphire'),
  (17, 'Amethyst'),
  (17, 'Catseye'),
  (17, 'Emerald'),
  (17, 'Obsidian'),
  (17, 'Rose Quartz'),
  (17, 'Ruby'),
  (17, 'Turquoise'),
  (20, 'Amethyst'),
  (20, 'Catseye'),
  (20, 'Citrine'),
  (20, 'Obsidian'),
  (20, 'Pearl'),
  (20, 'Rose Quartz'),
  (20, 'Sapphire'),
  (23, 'Amethyst'),
  (23, 'Citrine'),
  (23, 'Emerald'),
  (23, 'Obsidian'),
  (23, 'Pearl'),
  (23, 'Ruby'),
  (23, 'Sapphire'),
  (26, 'Amethyst'),
  (26, 'Catseye'),
  (26, 'Citrine'),
  (26, 'Emerald'),
  (26, 'Pearl'),
  (26, 'Rose Quartz'),
  (26, 'Ruby'),
  (29, 'Amethyst'),
  (29, 'Catseye'),
  (29, 'Emerald'),
  (29, 'Obsidian'),
  (29, 'Pearl'),
  (29, 'Rose Quartz'),
  (29, 'Sapphire'),
  (32, 'Amethyst'),
  (32, 'Catseye'),
  (32, 'Citrine'),
  (32, 'Obsidian'),
  (32, 'Pearl'),
  (32, 'Ruby'),
  (32, 'Turquoise'),
  (35, 'Amethyst'),
  (35, 'Catseye'),
  (35, 'Emerald'),
  (35, 'Obsidian'),
  (35, 'Rose Quartz'),
  (35, 'Ruby'),
  (35, 'Sapphire'),
  (38, 'Amethyst'),
  (38, 'Catseye'),
  (38, 'Citrine'),
  (38, 'Emerald'),
  (38, 'Obsidian'),
  (38, 'Pearl'),
  (38, 'Ruby'),
  (41, 'Amethyst'),
  (41, 'Citrine'),
  (41, 'Emerald'),
  (41, 'Pearl'),
  (41, 'Rose Quartz'),
  (41, 'Ruby'),
  (41, 'Sapphire'),
  (44, 'Amethyst'),
  (44, 'Catseye'),
  (44, 'Citrine'),
  (44, 'Obsidian'),
  (44, 'Pearl'),
  (44, 'Rose Quartz'),
  (44, 'Sapphire'),
  (47, 'Amethyst'),
  (47, 'Catseye'),
  (47, 'Emerald'),
  (47, 'Obsidian'),
  (47, 'Pearl'),
  (47, 'Rose Quartz'),
  (47, 'Sapphire'),
  (50, 'Amethyst'),
  (50, 'Catseye'),
  (50, 'Citrine'),
  (50, 'Emerald'),
  (50, 'Pearl'),
  (50, 'Ruby'),
  (50, 'Sapphire'),
  (53, 'Amethyst'),
  (53, 'Catseye'),
  (53, 'Citrine'),
  (53, 'Obsidian'),
  (53, 'Pearl'),
  (53, 'Rose Quartz'),
  (53, 'Ruby'),
  (56, 'Amethyst'),
  (56, 'Catseye'),
  (56, 'Emerald'),
  (56, 'Obsidian'),
  (56, 'Pearl'),
  (56, 'Ruby'),
  (56, 'Sapphire'),
  (59, 'Amethyst'),
  (59, 'Citrine'),
  (59, 'Emerald'),
  (59, 'Pearl'),
  (59, 'Rose Quartz'),
  (59, 'Ruby'),
  (59, 'Turquoise'),
  (62, 'Amethyst'),
  (62, 'Catseye'),
  (62, 'Citrine'),
  (62, 'Obsidian'),
  (62, 'Pearl'),
  (62, 'Rose Quartz'),
  (62, 'Sapphire'),
  (65, 'Amethyst'),
  (65, 'Citrine'),
  (65, 'Emerald'),
  (65, 'Pearl'),
  (65, 'Rose Quartz'),
  (65, 'Ruby'),
  (65, 'Sapphire'),
  (68, 'Amethyst'),
  (68, 'Catseye'),
  (68, 'Citrine'),
  (68, 'Emerald'),
  (68, 'Obsidian'),
  (68, 'Pearl'),
  (68, 'Ruby'),
  (71, 'Amethyst'),
  (71, 'Catseye'),
  (71, 'Citrine'),
  (71, 'Obsidian'),
  (71, 'Rose Quartz'),
  (71, 'Ruby'),
  (71, 'Sapphire'),
  (74, 'Amethyst'),
  (74, 'Catseye'),
  (74, 'Emerald'),
  (74, 'Obsidian'),
  (74, 'Pearl'),
  (74, 'Rose Quartz'),
  (74, 'Sapphire'),
  (77, 'Amethyst'),
  (77, 'Catseye'),
  (77, 'Citrine'),
  (77, 'Emerald'),
  (77, 'Pearl'),
  (77, 'Ruby'),
  (77, 'Turquoise'),
  (80, 'Amethyst'),
  (80, 'Catseye'),
  (80, 'Citrine'),
  (80, 'Obsidian'),
  (80, 'Pearl'),
  (80, 'Rose Quartz'),
  (80, 'Ruby'),
  (83, 'Amethyst'),
  (83, 'Catseye'),
  (83, 'Emerald'),
  (83, 'Pearl'),
  (83, 'Rose Quartz'),
  (83, 'Ruby'),
  (83, 'Sapphire'),
  (86, 'Amethyst'),
  (86, 'Catseye'),
  (86, 'Citrine'),
  (86, 'Obsidian'),
  (86, 'Rose Quartz'),
  (86, 'Ruby'),
  (86, 'Sapphire'),
  (89, 'Amethyst'),
  (89, 'Catseye'),
  (89, 'Citrine'),
  (89, 'Emerald'),
  (89, 'Pearl'),
  (89, 'Ruby'),
  (89, 'Turquoise'),
  (92, 'Amethyst'),
  (92, 'Catseye'),
  (92, 'Citrine'),
  (92, 'Emerald'),
  (92, 'Obsidian'),
  (92, 'Pearl'),
  (92, 'Rose Quartz'),
  (95, 'Amethyst'),
  (95, 'Catseye'),
  (95, 'Emerald'),
  (95, 'Pearl'),
  (95, 'Rose Quartz'),
  (95, 'Ruby'),
  (95, 'Sapphire'),
  (98, 'Amethyst'),
  (98, 'Citrine'),
  (98, 'Emerald'),
  (98, 'Pearl'),
  (98, 'Rose Quartz'),
  (98, 'Ruby'),
  (98, 'Sapphire'),
  (101, 'Amethyst'),
  (101, 'Catseye'),
  (101, 'Citrine'),
  (101, 'Emerald'),
  (101, 'Pearl'),
  (101, 'Rose Quartz'),
  (101, 'Ruby'),
  (104, 'Amethyst'),
  (104, 'Catseye'),
  (104, 'Citrine'),
  (104, 'Obsidian'),
  (104, 'Pearl'),
  (104, 'Rose Quartz'),
  (104, 'Sapphire'),
  (107, 'Amethyst'),
  (107, 'Catseye'),
  (107, 'Citrine'),
  (107, 'Emerald'),
  (107, 'Obsidian'),
  (107, 'Pearl'),
  (107, 'Ruby'),
  (110, 'Amethyst'),
  (110, 'Catseye'),
  (110, 'Citrine'),
  (110, 'Emerald'),
  (110, 'Pearl'),
  (110, 'Rose Quartz'),
  (110, 'Sapphire'),
  (113, 'Amethyst'),
  (113, 'Catseye'),
  (113, 'Citrine'),
  (113, 'Obsidian'),
  (113, 'Pearl'),
  (113, 'Ruby'),
  (113, 'Sapphire'),
  (116, 'Amethyst'),
  (116, 'Catseye'),
  (116, 'Citrine'),
  (116, 'Emerald'),
  (116, 'Obsidian'),
  (116, 'Rose Quartz'),
  (116, 'Ruby'),
  (119, 'Amethyst'),
  (119, 'Catseye'),
  (119, 'Citrine'),
  (119, 'Emerald'),
  (119, 'Pearl'),
  (119, 'Rose Quartz'),
  (119, 'Sapphire'),
  (122, 'Amethyst'),
  (122, 'Catseye'),
  (122, 'Citrine'),
  (122, 'Obsidian'),
  (122, 'Pearl'),
  (122, 'Ruby'),
  (122, 'Sapphire'),
  (125, 'Amethyst'),
  (125, 'Catseye'),
  (125, 'Citrine'),
  (125, 'Emerald'),
  (125, 'Pearl'),
  (125, 'Rose Quartz'),
  (125, 'Ruby'),
  (128, 'Amethyst'),
  (128, 'Catseye'),
  (128, 'Citrine'),
  (128, 'Emerald'),
  (128, 'Obsidian'),
  (128, 'Pearl'),
  (128, 'Sapphire'),
  (131, 'Amethyst'),
  (131, 'Catseye'),
  (131, 'Citrine'),
  (131, 'Obsidian'),
  (131, 'Pearl'),
  (131, 'Rose Quartz'),
  (131, 'Ruby'),
  (134, 'Amethyst'),
  (134, 'Catseye'),
  (134, 'Citrine'),
  (134, 'Emerald'),
  (134, 'Pearl'),
  (134, 'Rose Quartz'),
  (134, 'Sapphire'),
  (137, 'Amethyst'),
  (137, 'Catseye'),
  (137, 'Citrine'),
  (137, 'Obsidian'),
  (137, 'Pearl'),
  (137, 'Ruby'),
  (137, 'Turquoise'),
  (140, 'Amethyst'),
  (140, 'Catseye'),
  (140, 'Citrine'),
  (140, 'Emerald'),
  (140, 'Pearl'),
  (140, 'Rose Quartz'),
  (140, 'Sapphire'),
  (143, 'Amethyst'),
  (143, 'Catseye'),
  (143, 'Citrine'),
  (143, 'Emerald'),
  (143, 'Obsidian'),
  (143, 'Pearl'),
  (143, 'Ruby'),
  (146, 'Amethyst'),
  (146, 'Catseye'),
  (146, 'Citrine'),
  (146, 'Emerald'),
  (146, 'Pearl'),
  (146, 'Rose Quartz'),
  (146, 'Sapphire'),
  (149, 'Amethyst'),
  (149, 'Catseye'),
  (149, 'Citrine'),
  (149, 'Emerald'),
  (149, 'Obsidian'),
  (149, 'Pearl'),
  (149, 'Ruby');
